import { createContext, useContext, useState, useEffect, type ReactNode } from 'react';

type Language = 'vi' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translation data
const translations = {
  vi: {
  // Admin
  'admin.gallery.title': 'Quản lý Hình ảnh',
  'admin.gallery.upload': 'Tải lên hình ảnh',
  'admin.gallery.uploading': 'Đang tải lên...',
  'admin.gallery.delete': 'Xóa',
  'admin.gallery.upload_new': 'Tải Lên Hình Ảnh Mới',
  'admin.gallery.firebase_desc': 'Hình ảnh được tải lên Firebase Storage và lưu vào chỉ mục hiển thị.',
  'admin.gallery.no_firebase': 'Firebase chưa được cấu hình — hình ảnh được lưu dưới dạng data URLs để xem trước.',
  'admin.gallery.upload_button': 'Tải Lên',
  'admin.gallery.choose_file': 'Chọn Tệp',
  'admin.gallery.no_file': 'Chưa chọn tệp',
  'admin.gallery.no_images': 'Chưa có hình ảnh trong thư viện. Tải lên một số hình ảnh để bắt đầu.',
  'admin.gallery.edit': 'Chỉnh sửa',
  'admin.gallery.save': 'Lưu',
  'admin.gallery.cancel': 'Hủy',
  'admin.gallery.name': 'Tên',
  'admin.gallery.date': 'Ngày',
  'admin.gallery.confirm_delete': 'Bạn có chắc chắn muốn xóa hình ảnh này?',
  'admin.gallery.error_load': 'Không thể tải hình ảnh',
  'admin.gallery.error_upload': 'Không thể tải lên hình ảnh. Vui lòng thử lại.',
  'admin.gallery.error_update': 'Không thể cập nhật hình ảnh',
  'admin.gallery.error_delete': 'Không thể xóa hình ảnh',
    'admin.login': 'Đăng nhập Admin',
    'admin.dashboard': 'Quản trị Website',
    'admin.logout': 'Đăng xuất',
    'admin.manage_reflections': 'Quản lý Phúc Âm',
    'admin.manage_events': 'Quản lý Sự kiện',
    'admin.manage_gallery': 'Quản lý Hình ảnh',
  // Navigation
  'nav.home': 'Trang chủ',
  'nav.about': 'Giới thiệu',
  'nav.ministries': 'Ban Ngành',
  'nav.events': 'Sự kiện',
  'nav.gallery': 'Hình ảnh',
  'nav.reflections': 'Phúc Âm',
  'nav.give': 'Ủng Hộ',
  'nav.contact': 'Liên hệ',
  // Gallery
  'gallery.title': 'Thư Viện Hình Ảnh',
  'gallery.subtitle': 'Xem lại những khoảnh khắc đẹp và hoạt động của cộng đoàn qua các hình ảnh được cập nhật thường xuyên.',
  'gallery.empty': 'Chưa có hình ảnh nào được đăng tải.',
    
    // Homepage
    'home.title': 'Cộng Đoàn Công Giáo Việt Nam Thánh Anê Lê Thị Thành',
    'home.subtitle': 'Chào mừng quý vị đến với cộng đoàn nhỏ bé của chúng tôi tại Melbourne!',
    'home.description': 'Mục tiêu của cộng đoàn là sống theo tinh thần Tin Mừng trong đoàn kết, yêu thương và phục vụ.',
    'home.mass': 'Thánh Lễ Chúa Nhật',
    'home.mass_time': 'Thánh Lễ Chúa Nhật lúc 5:00 PM tại 138 Woodhouse Grove, Box Hill North VIC 3129.',
    'home.welcome_badge': 'Chào mừng',
    'home.location': 'Địa điểm',
    'home.location_short': 'Box Hill North',
    'home.church_name': 'Giáo xứ Thánh Anê Lê Thị Thành',
    'home.address_short': '138 Woodhouse Grove, Box Hill North',
    'home.weekly_worship': 'Các Thánh Lễ Hàng Tuần',
    'home.visit_contact': 'Ghé Thăm & Liên Hệ',
    'home.learn_more': 'Tìm hiểu thêm',
    'home.contact_us': 'Liên hệ với chúng tôi',
    
    // Rich Text Editor
    'Rich Text Editor': 'Trình soạn thảo văn bản phong phú',
    'Enter URL': 'Nhập URL',
    'Bold (Ctrl+B)': 'Đậm (Ctrl+B)',
    'Italic (Ctrl+I)': 'Nghiêng (Ctrl+I)',
    'Underline (Ctrl+U)': 'Gạch chân (Ctrl+U)',
    'Bullet List': 'Danh sách gạch đầu dòng',
    'Numbered List': 'Danh sách số',
    'Link (Ctrl+K)': 'Liên kết (Ctrl+K)',
    'Clear Formatting': 'Xóa định dạng',
    'Tip: You can paste formatted content directly from Facebook, Word, or other platforms': 'Mẹo: Bạn có thể dán nội dung đã định dạng trực tiếp từ Facebook, Word hoặc các nền tảng khác',
    'Language': 'Ngôn ngữ',
    
    // Modern Rich Text Editor
    'Tip: Paste with Ctrl+V to preserve formatting from Facebook, Word, or other platforms': 'Mẹo: Dán với Ctrl+V để giữ nguyên định dạng từ Facebook, Word hoặc các nền tảng khác',
    
    // Common
    'common.read_more': 'Đọc thêm',
    'common.view_all': 'Xem tất cả',
    'common.contact': 'Liên hệ',
    'common.phone': 'Điện thoại',
    'common.email': 'Email',
    'common.address': 'Địa chỉ',
    
    // Events
    'events.title': 'Sự Kiện Cộng Đoàn',
    'events.subtitle': 'Theo dõi và tham gia các sự kiện sắp tới của cộng đoàn. Cùng nhau xây dựng một cộng đoàn gắn kết và phát triển.',
    'events.upcoming': 'Sắp diễn ra',
    'events.past': 'Đã diễn ra',
    'events.all': 'Tất cả sự kiện',
    'events.next_event': 'Sự Kiện Sắp Diễn Ra',
    'events.latest_event': 'Sự kiện gần nhất',
    'events.view_details': 'Xem thêm',
    'events.no_upcoming': 'Không có sự kiện sắp tới.',
    'events.no_events': 'Chưa có sự kiện nào được tạo.',
    'events.date': 'Ngày',
    'events.time': 'Giờ',
    'events.location': 'Địa điểm',
    'events.details': 'Chi Tiết Sự Kiện',
    'events.links': 'Liên Kết',
    'events.video': 'Video',
    'events.back_to_events': 'Quay lại Sự kiện',
    'events.not_found': 'Không tìm thấy sự kiện',
    'events.not_found_desc': 'Sự kiện này không tồn tại hoặc đã bị xóa.',
    
    // Reflections
    'reflections.title': 'Phúc Âm & Suy Niệm',
    'reflections.subtitle': 'Chia sẻ lời Chúa và những suy niệm tâm linh để nuôi dưỡng đời sống đức tin. Cùng nhau lắng nghe và sống theo lời Thiên Chúa.',
    'reflections.search': 'Tìm kiếm',
    'reflections.search_placeholder': 'Tìm theo tiêu đề hoặc nội dung...',
    'reflections.author': 'Tác giả',
    'reflections.all_authors': 'Tất cả tác giả',
    'reflections.sort': 'Sắp xếp',
    'reflections.newest': 'Mới nhất',
    'reflections.oldest': 'Cũ nhất',
    'reflections.by_title': 'Theo tiêu đề',
    'reflections.showing': 'Hiển thị',
    'reflections.of': '/',
    'reflections.reflections': 'bài suy niệm',
    'reflections.no_results': 'Không tìm thấy kết quả',
    'reflections.no_results_desc': 'Thử thay đổi từ khóa tìm kiếm hoặc bộ lọc.',
    'reflections.clear_filters': 'Xóa bộ lọc',
    'reflections.no_reflections': 'Chưa có bài suy niệm nào',
    'reflections.no_reflections_desc': 'Các bài suy niệm và chia sẻ Phúc Âm sẽ được cập nhật thường xuyên.',
    'reflections.gospel': 'Phúc Âm',
    'reflections.read_more': 'Đọc thêm →',
    'reflections.recently': 'Gần đây',
    'reflections.featured': 'Suy Niệm Nổi Bật',
    'reflections.all_reflections': 'Tất Cả Suy Niệm',
    'reflections.back_to_list': 'Quay lại danh sách',
    'reflections.edit_admin': 'Chỉnh sửa (Admin)',
    
    // Give
    'give.title': 'Ủng Hộ Cộng Đoàn',
    'give.subtitle': 'Cảm ơn lòng hảo tâm của quý vị. Sự đóng góp của quý vị giúp cộng đoàn duy trì các hoạt động tôn giáo và phục vụ cộng đồng.',
    'give.support_community': 'Ủng Hộ Cộng Đoàn',
    'give.bank_transfer': 'Chuyển khoản ngân hàng',
    'give.cash_donation': 'Ủng hộ trực tiếp',
    'give.bank_transfer_title': 'Chuyển Khoản Ngân Hàng',
    'give.bank_transfer_desc': 'Quý vị có thể ủng hộ cộng đoàn qua chuyển khoản ngân hàng với thông tin sau:',
    'give.cash_donation_title': 'Ủng Hộ Trực Tiếp',
    'give.account_name': 'Tên Tài Khoản',
    'give.bsb': 'BSB',
    'give.account_number': 'Số Tài Khoản',
    'give.reference': 'Ghi Chú Quan Trọng',
    'give.reference_note': 'Vui lòng ghi: Tên của quý vị + "Ung ho CGVN Anê Thành"',
    'give.cash_description': 'Quý vị có thể ủng hộ trực tiếp bằng tiền mặt trong các dịp:',
    'give.sunday_mass': 'Trong Thánh Lễ Chúa Nhật',
    'give.special_occasions': 'Các dịp lễ đặc biệt',
    'give.meet_committee': 'Gặp trực tiếp Ban Chấp hành',
    'give.contact_title': 'Có Câu Hỏi?',
    'give.contact_description': 'Nếu quý vị cần hỗ trợ hoặc có câu hỏi về việc ủng hộ, vui lòng liên hệ với chúng tôi:',
    'give.thank_you_title': 'Cảm Ơn Quý Vị',
    'give.thank_you_message': 'Mọi đóng góp của quý vị, dù lớn hay nhỏ, đều rất ý nghĩa và giúp cộng đoàn tiếp tục phát triển. Xin Chúa ban phúc lành đến quý vị và gia đình.',
    
    // About
    'about.title': 'Giới thiệu về Cộng Đoàn Công Giáo Việt Nam Thánh Anê Lê Thị Thành',
    'about.welcome': 'Chào mừng quý vị và các bạn đến với trang điện tử của Cộng Đoàn Công Giáo Việt Nam Thánh Anê Lê Thị Thành (CĐCGVNAT). Là một cộng đoàn nhỏ bé (khoảng hơn 120 tín hữu), nhưng cộng đoàn có Thánh Lễ mỗi Chúa Nhật vào lúc 5 giờ chiều tại nhà thờ St. Clare Catholic Church.',
    'about.history_title': 'Lịch Sử Hình Thành',
    'about.history_milestone_1': 'Khởi Đầu - 2013 tại St. Timothy',
    'about.history_milestone_2': 'Chuyển đến St. Clare - 2026',
    'about.history_p1': 'Cộng đoàn được thành lập vào năm 2013, bắt đầu từ một nhóm nhỏ các gia đình Công Giáo Việt Nam sinh sống tại khu vực Vermont và vùng phụ cận. Với sự chấp thuận của Tổng Giáo Phận Melbourne, cộng đoàn đã được phép tổ chức Thánh Lễ tiếng Việt tại nhà thờ St. Timothy. Năm 2026, cộng đoàn chuyển đến nhà thờ St. Clare tại Box Hill North để tiếp tục sinh hoạt và phát triển.',
    'about.history_p2': 'Qua thời gian, cộng đoàn đã phát triển từ vài chục người ban đầu lên đến hơn 120 tín hữu hiện nay. Điều đáng mừng là số lượng các gia đình trẻ và thiếu nhi trong cộng đoàn ngày càng tăng, mang đến sinh khí mới cho cộng đoàn.',
    'about.mission_vision': 'Sứ Mệnh & Tầm Nhìn',
    'about.mission': 'Sứ Mệnh',
    'about.vision': 'Tầm Nhìn',
    'about.mission_1': 'Duy trì và phát triển đức tin Công Giáo trong cộng đồng người Việt',
    'about.mission_2': 'Giáo dục đức tin cho thế hệ trẻ',
    'about.mission_3': 'Phục vụ cộng đồng và lan tỏa tình yêu của Chúa',
    'about.vision_1': 'Xây dựng một cộng đoàn vững mạnh trong đức tin',
    'about.vision_2': 'Kết nối các thế hệ trong cộng đồng Công Giáo Việt Nam',
    'about.vision_3': 'Là điểm tựa tinh thần cho người Công Giáo Việt Nam xa xứ',
    'about.activities_title': 'Sinh Hoạt Cộng Đoàn',
    'about.activities_desc': 'Cộng đoàn có nhiều hoạt động đa dạng nhằm nuôi dưỡng đức tin và xây dựng tinh thần cộng đồng.',
    'about.liturgy': 'Phụng Vụ',
    'about.education': 'Giáo Dục Đức Tin',
    'about.community': 'Hoạt Động Cộng Đồng',
    'about.liturgy_1': 'Thánh Lễ Chúa Nhật hàng tuần',
    'about.liturgy_2': 'Các nghi thức phụng vụ đặc biệt',
    'about.liturgy_3': 'Thánh ca và đọc sách thánh',
    'about.education_1': 'Lớp giáo lý cho thiếu nhi',
    'about.education_2': 'Sinh hoạt giới trẻ',
    'about.education_3': 'Học hỏi Kinh Thánh',
    'about.community_1': 'Thăm viếng người già và bệnh nhân',
    'about.community_2': 'Các hoạt động từ thiện xã hội',
    'about.community_3': 'Tổ chức các sự kiện cộng đồng',
    'about.leadership': 'Ban Mục Vụ',
    'about.leadership_desc': 'Ban Mục Vụ hiện tại của cộng đoàn gồm các thành viên nhiệt thành, tận tụy phục vụ dưới sự hướng dẫn của cha Tuyên Úy. Các thành viên Ban Mục Vụ luôn sẵn sàng lắng nghe và phục vụ nhu cầu của anh chị em giáo dân trong cộng đoàn.',
    'about.join_title': 'Tham Gia Cùng Chúng Tôi',
    'about.join_desc': 'Cộng đoàn luôn rộng mở chào đón các anh chị em mới. Nếu bạn muốn tìm hiểu thêm hoặc tham gia các hoạt động của cộng đoàn, xin đừng ngần ngại liên hệ với chúng tôi.',
    'about.call': 'Gọi Điện',
    'about.email': 'Gửi Email',
    
    // Contact
    'contact.title': 'Liên hệ',
    'contact.get_in_touch': 'Liên Hệ Ngay',
    'contact.description': 'Nếu bạn có câu hỏi hoặc cần hỗ trợ, hãy liên hệ với chúng tôi qua các thông tin dưới đây hoặc đến tham dự Thánh Lễ vào Chúa Nhật hàng tuần.',
    'contact.address': 'Địa chỉ',
    'contact.mass': 'Thánh Lễ',
    'contact.phone': 'Điện thoại',
    'contact.email': 'Email',
    'contact.facebook': 'Facebook:',
    'contact.send_message': 'Gửi Tin Nhắn',
    'contact.name': 'Họ và Tên',
    'contact.name_placeholder': 'Nhập họ và tên',
    'contact.email_placeholder': 'Nhập email',
    'contact.phone_placeholder': 'Nhập số điện thoại',
    'contact.subject': 'Chủ đề',
    'contact.subject_placeholder': 'Nhập chủ đề',
    'contact.message': 'Nội dung',
    'contact.message_placeholder': 'Nhập nội dung tin nhắn...',
    'contact.send_button': 'Gửi Tin Nhắn',
    'contact.success_message': 'Cảm ơn bạn! Tin nhắn đã được gửi thành công.',
    'contact.connect_with_us': 'Kết Nối Với Chúng Tôi',
    'contact.find_us': 'Tìm Chúng Tôi',
    'contact.open_map': 'Mở Google Maps',
    
    // Ministries
    'ministries.title': 'Mục Vụ',
    'ministries.description': 'Cộng đoàn Thánh Anê Lê Thị Thành có nhiều ban mục vụ khác nhau phục vụ nhu cầu tâm linh và đời sống của giáo dân.',
    'ministries.serving_together': 'Cùng Nhau Phục Vụ',
    'ministries.join_title': 'Tham Gia Phục Vụ',
    'ministries.join_desc': 'Mỗi thành viên trong cộng đoàn đều có ơn gọi phục vụ. Hãy tham gia vào các ban mục vụ để cùng nhau xây dựng Vương Quốc Thiên Chúa.',
    'ministries.activities': 'Hoạt Động',
    'ministries.get_involved': 'Tham Gia Cùng Chúng Tôi',
    'ministries.get_involved_desc': 'Nếu bạn muốn tham gia phục vụ hoặc tìm hiểu thêm về các ban mục vụ, xin vui lòng liên hệ với chúng tôi.',
    'ministries.call_us': 'Gọi Cho Chúng Tôi',
    'ministries.email_us': 'Gửi Email',
    
    'ministries.safeguarding_title': 'Chính Sách An Toàn',
    'ministries.safeguarding_heading': 'Cam Kết Bảo Vệ Trẻ Em & Người Dễ Bị Tổn Thương',
    'ministries.safeguarding_desc': 'Chúng tôi cam kết tạo ra một môi trường an toàn và hỗ trợ cho tất cả mọi người, đặc biệt là trẻ em và những người dễ bị tổn thương. Vui lòng xem chính sách chi tiết của chúng tôi.',
    'ministries.download_policy': 'Tải Xuống Chính Sách (PDF)',
    
    'ministries.family': 'Mục Vụ Gia Đình',
    'ministries.family_desc': 'Tổ chức các hoạt động cho gia đình và trẻ em trong cộng đoàn, giúp xây dựng gia đình Công Giáo vững mạnh.',
    'ministries.family_activity_1': 'Tổ chức các buổi họp mặt gia đình',
    'ministries.family_activity_2': 'Lớp giáo lý cho trẻ em',
    'ministries.family_activity_3': 'Hỗ trợ và tư vấn gia đình',
    
    'ministries.liturgy': 'Mục Vụ Phụng Vụ',
    'ministries.liturgy_desc': 'Chuẩn bị và phục vụ trong các thánh lễ và nghi thức tôn giáo, đảm bảo phụng vụ được cử hành trang nghiêm.',
    'ministries.liturgy_activity_1': 'Phục vụ trong Thánh Lễ (đọc sách, dâng lễ vật)',
    'ministries.liturgy_activity_2': 'Chuẩn bị và trang trí bàn thờ',
    'ministries.liturgy_activity_3': 'Tổ chức các nghi lễ đặc biệt',
    
    'ministries.music': 'Ca Đoàn',
    'ministries.music_desc': 'Phục vụ âm nhạc trong thánh lễ và các dịp lễ đặc biệt, góp phần làm cho phụng vụ thêm trang nghiêm.',
    'ministries.music_activity_1': 'Ca hát trong Thánh Lễ Chúa Nhật',
    'ministries.music_activity_2': 'Luyện tập thánh ca hàng tuần',
    'ministries.music_activity_3': 'Phục vụ trong các dịp lễ đặc biệt',
    
    'ministries.charity': 'Mục Vụ Từ Thiện',
    'ministries.charity_desc': 'Hỗ trợ những người có hoàn cảnh khó khăn trong cộng đoàn và xã hội, thực hiện tình yêu thương của Chúa.',
    'ministries.charity_activity_1': 'Thăm viếng và giúp đỡ người nghèo',
    'ministries.charity_activity_2': 'Quyên góp và phân phát quà từ thiện',
    'ministries.charity_activity_3': 'Tổ chức các chương trình từ thiện',
    
    'ministries.youth': 'Mục Vụ Giới Trẻ',
    'ministries.youth_desc': 'Tổ chức các hoạt động cho thanh thiếu niên, giúp các bạn trẻ phát triển đức tin và kỹ năng sống.',
    'ministries.youth_activity_1': 'Sinh hoạt giới trẻ định kỳ',
    'ministries.youth_activity_2': 'Trại hè và các hoạt động ngoại khóa',
    'ministries.youth_activity_3': 'Học hỏi Kinh Thánh và giáo lý',
    
    'ministries.evangelization': 'Mục Vụ Truyền Giáo',
    'ministries.evangelization_desc': 'Rao giảng Tin Mừng và mời gọi mọi người đến với Chúa Kitô, lan tỏa đức tin trong cộng đồng.',
    'ministries.evangelization_activity_1': 'Tổ chức các buổi chia sẻ đức tin',
    'ministries.evangelization_activity_2': 'Chào đón và hướng dẫn tân tòng',
    'ministries.evangelization_activity_3': 'Phát tài liệu và sách đạo',
    
    // Homepage additional sections
    'home.welcome_title': 'Chào Mừng Đến Với Cộng Đoàn',
    'home.faith_title': 'Đức Tin',
    'home.faith_desc': 'Cùng nhau thờ phượng và tăng trưởng trong đức tin Công Giáo',
    'home.community_title': 'Cộng Đồng',
    'home.community_desc': 'Xây dựng mối quan hệ thân thiết trong cộng đoàn người Việt',
    'home.service_title': 'Phục Vụ',
    'home.service_desc': 'Cùng nhau phục vụ và lan tỏa tình yêu của Chúa',
    'home.mass_schedule_title': 'Giờ Lễ & Địa Điểm',
    'home.mass_schedule_subtitle': 'Lịch Thánh Lễ',
    'home.sunday': 'Chúa Nhật:',
    'home.sunday_time': '5:00pm - 6:00pm',
    'home.special_days': 'Các ngày lễ trọng:',
    'home.special_days_desc': 'Theo thông báo',
    'home.confession': 'Xưng tội:',
    'home.confession_time': 'Trước Thánh Lễ 30 phút',
    'home.info_title': 'Thông Tin',
    'home.address_label': 'Địa chỉ:',
    'home.address_value': 'St Clare Catholic Church, 138 Woodhouse Grove, Box Hill North VIC 3129',
    'home.parking_label': 'Bãi đậu xe:',
    'home.parking_desc': 'Có chỗ đậu xe miễn phí trong khuôn viên nhà thờ',
    'home.contact_label': 'Liên hệ:',
    'home.upcoming_events': 'Sự Kiện Sắp Tới',
    'home.important_event': 'Sự kiện quan trọng sắp diễn ra',
    'home.featured_event': 'Sự Kiện Nổi Bật',
    'home.other_events': 'Các sự kiện sắp tới khác',
    'home.details': 'Chi tiết',
    'home.view_all_events': 'Xem tất cả sự kiện',
    'home.ministries_title': 'Mục Vụ',
    'home.children_ministry': 'Thiếu Nhi',
    'home.children_desc': 'Giáo lý và sinh hoạt cho các em nhỏ',
    'home.youth_ministry': 'Giới Trẻ',
    'home.youth_desc': 'Hoạt động và chia sẻ cho người trẻ',
    'home.family_ministry': 'Gia Đình',
    'home.family_desc': 'Đồng hành cùng các gia đình trẻ',
    'home.choir_ministry': 'Ca Đoàn',
    'home.choir_desc': 'Phục vụ thánh ca trong Thánh Lễ',
    'home.latest_content': 'Phúc Âm Mới',
    'home.gospel': 'Phúc Âm',
    'home.read_more': 'Đọc tiếp',
    'home.view_all_gospel': 'Xem tất cả bài Phúc Âm',
    'home.connect': 'Kết Nối',
    'home.follow_us': 'Theo dõi chúng tôi',
    'home.facebook': 'Facebook',
    'home.email': 'Email',
    'home.contact_direct': 'Liên hệ trực tiếp',
    'home.join_us_title': 'Tham Gia Cùng Chúng Tôi',
    'home.join_us_desc': 'Chúng tôi luôn chào đón thành viên mới tham gia vào cộng đoàn. Hãy đến dự Thánh Lễ và tham gia các hoạt động của cộng đoàn!',
    'home.contact_now': 'Liên Hệ Ngay',
    'home.learn_more_about': 'Tìm Hiểu Thêm',
    
    // Footer
    'footer.copyright': 'Cộng Đoàn Công Giáo Việt Nam Thánh Anê Lê Thị Thành. Đã đăng ký bản quyền.',
    'footer.about': 'Giới thiệu',
    'footer.contact': 'Liên hệ',
    'footer.description': 'Cộng đoàn Công Giáo Việt Nam Thánh Anê Lê Thị Thành phục vụ cộng đồng với đức tin, hy vọng và tình yêu thương.',
    'footer.quick_links': 'Liên Kết Nhanh',
    'footer.contact_us': 'Liên Hệ',
    'footer.mass_times': 'Giờ Lễ',
    'footer.back_to_top': 'Lên Đầu Trang',
    'footer.privacy': 'Chính Sách Bảo Mật',
    'footer.terms': 'Điều Khoản',
    'footer.sitemap': 'Sơ Đồ Trang',
  },
  en: {
  // Admin
  'admin.gallery.title': 'Manage Gallery',
  'admin.gallery.upload': 'Upload Image',
  'admin.gallery.uploading': 'Uploading...',
  'admin.gallery.delete': 'Delete',
  'admin.gallery.upload_new': 'Upload New Image',
  'admin.gallery.firebase_desc': 'Images are uploaded to Firebase Storage and indexed for display.',
  'admin.gallery.no_firebase': 'Firebase not configured — images are stored as data URLs locally for preview only.',
  'admin.gallery.upload_button': 'Upload',
  'admin.gallery.choose_file': 'Choose File',
  'admin.gallery.no_file': 'No file chosen',
  'admin.gallery.no_images': 'No images in the gallery yet. Upload some images to get started.',
  'admin.gallery.edit': 'Edit',
  'admin.gallery.save': 'Save',
  'admin.gallery.cancel': 'Cancel',
  'admin.gallery.name': 'Name',
  'admin.gallery.date': 'Date',
  'admin.gallery.confirm_delete': 'Are you sure you want to delete this image?',
  'admin.gallery.error_load': 'Failed to load gallery images',
  'admin.gallery.error_upload': 'Failed to upload image. Please try again.',
  'admin.gallery.error_update': 'Failed to update image',
  'admin.gallery.error_delete': 'Failed to delete image',
    'admin.login': 'Admin Login',
    'admin.dashboard': 'Website Admin',
    'admin.logout': 'Logout',
    'admin.manage_reflections': 'Manage Gospel',
    'admin.manage_events': 'Manage Events',
    'admin.manage_gallery': 'Manage Gallery',
  // Navigation
  'nav.home': 'Home',
  'nav.about': 'About',
  'nav.ministries': 'Ministries',
  'nav.events': 'Events',
  'nav.gallery': 'Gallery',
  'nav.reflections': 'Gospel',
  'nav.give': 'Give',
  'nav.contact': 'Contact',
  // Gallery
  'gallery.title': 'Image Gallery',
  'gallery.subtitle': 'Browse beautiful moments and community activities through regularly updated images.',
  'gallery.empty': 'No images have been uploaded yet.',
    
    // Homepage
    'home.title': 'Vietnamese Catholic Community St Ane Le Thi Thanh',
    'home.subtitle': 'Welcome to our small community in Melbourne!',
    'home.description': 'Our goal is to live according to the Gospel spirit in unity, love and service.',
    'home.welcome_badge': 'Welcome',
    'home.mass': 'Sunday Mass',
    'home.mass_time': 'Sunday Mass at 5:00 PM at 138 Woodhouse Grove, Box Hill North VIC 3129.',
    'home.location': 'Location',
    'home.location_short': 'Box Hill North',
    'home.church_name': 'St Clare Catholic Church',
    'home.address_short': '138 Woodhouse Grove, Box Hill North',
    'home.weekly_worship': 'Weekly Worship Services',
    'home.visit_contact': 'Visit & Contact Us',
    'home.learn_more': 'Learn More',
    'home.contact_us': 'Contact Us',
    
    // Common
    'common.read_more': 'Read More',
    'common.view_all': 'View All',
    'common.contact': 'Contact',
    'common.phone': 'Phone',
    'common.email': 'Email',
    'common.address': 'Address',
    
    // Events
    'events.title': 'Community Events',
    'events.subtitle': 'Follow and participate in upcoming community events. Together we build a connected and thriving community.',
    'events.upcoming': 'Upcoming',
    'events.past': 'Past',
    'events.all': 'All Events',
    'events.next_event': 'Upcoming Events',
    'events.latest_event': 'Next event',
    'events.view_details': 'Read more',
    'events.no_upcoming': 'No upcoming events.',
    'events.no_events': 'No events have been created yet.',
    'events.date': 'Date',
    'events.time': 'Time',
    'events.location': 'Location',
    'events.details': 'Event Details',
    'events.links': 'Links',
    'events.video': 'Video',
    'events.back_to_events': 'Back to Events',
    'events.not_found': 'Event Not Found',
    'events.not_found_desc': 'This event does not exist or has been removed.',
    
    // Reflections
    'reflections.title': 'Gospel & Reflections',
    'reflections.subtitle': 'Share God\'s word and spiritual reflections to nourish faith life. Together we listen and live according to God\'s word.',
    'reflections.search': 'Search',
    'reflections.search_placeholder': 'Search by title or content...',
    'reflections.author': 'Author',
    'reflections.all_authors': 'All authors',
    'reflections.sort': 'Sort',
    'reflections.newest': 'Newest',
    'reflections.oldest': 'Oldest',
    'reflections.by_title': 'By Title',
    'reflections.showing': 'Showing',
    'reflections.of': '/',
    'reflections.reflections': 'reflections',
    'reflections.no_results': 'No results found',
    'reflections.no_results_desc': 'Try changing your search keywords or filters.',
    'reflections.clear_filters': 'Clear filters',
    'reflections.no_reflections': 'No reflections yet',
    'reflections.no_reflections_desc': 'Gospel reflections and shares will be updated regularly.',
    'reflections.gospel': 'Gospel',
    'reflections.read_more': 'Read more',
    'reflections.recently': 'Recently',
    'reflections.featured': 'Featured Reflection',
    'reflections.all_reflections': 'All Reflections',
    'reflections.back_to_list': 'Back to list',
    'reflections.edit_admin': 'Edit (Admin)',
    
    // Give
    'give.title': 'Support Our Community',
    'give.subtitle': 'Thank you for your generosity. Your contributions help our community maintain religious activities and serve the community.',
    'give.support_community': 'Support Community',
    'give.bank_transfer': 'Bank Transfer',
    'give.cash_donation': 'Direct Donation',
    'give.bank_transfer_title': 'Bank Transfer',
    'give.bank_transfer_desc': 'You can support the community through bank transfer with the following information:',
    'give.cash_donation_title': 'Cash Donation',
    'give.account_name': 'Account Name',
    'give.bsb': 'BSB',
    'give.account_number': 'Account Number',
    'give.reference': 'Important Note',
    'give.reference_note': 'Please include: Your name + "Donation CGVN Anê Thành"',
    'give.cash_description': 'You can donate directly with cash on the following occasions:',
    'give.sunday_mass': 'During Sunday Mass',
    'give.special_occasions': 'Special feast days',
    'give.meet_committee': 'Meet directly with the Committee',
    'give.contact_title': 'Have Questions?',
    'give.contact_description': 'If you need assistance or have questions about donations, please contact us:',
    'give.thank_you_title': 'Thank You',
    'give.thank_you_message': 'Every contribution, big or small, is meaningful and helps our community continue to grow. May God bless you and your family.',
    
    // About
    'about.title': 'About Vietnamese Catholic Community St Ane Le Thi Thanh',
    'about.welcome': 'Welcome to the website of the Vietnamese Catholic Community St Ane Le Thi Thanh (VCCNAT). We are a small community (about 120+ faithful), but we have Sunday Mass every week at 5:00 PM at St. Clare Catholic Church.',
    'about.history_title': 'Formation History',
    'about.history_milestone_1': 'The Beginning - 2013 at St. Timothy',
    'about.history_milestone_2': 'Move to St. Clare',
    'about.history_p1': 'The community was established in 2013, starting from a small group of Vietnamese Catholic families living in the Vermont area and surrounding regions. With the approval of the Archdiocese of Melbourne, the community was permitted to organize Vietnamese Mass at St. Timothy Church. The community has now moved to St. Clare Church in Box Hill North to continue our activities and growth.',
    'about.history_p2': 'Over time, the community has grown from a few dozen people initially to over 120 faithful today. What is encouraging is that the number of young families and children in the community is increasing, bringing new vitality to the community.',
    'about.mission_vision': 'Mission & Vision',
    'about.mission': 'Mission',
    'about.vision': 'Vision',
    'about.mission_1': 'Maintain and develop Catholic faith in the Vietnamese community',
    'about.mission_2': 'Educate faith for the younger generation',
    'about.mission_3': 'Serve the community and spread God\'s love',
    'about.vision_1': 'Build a strong community in faith',
    'about.vision_2': 'Connect generations in the Vietnamese Catholic community',
    'about.vision_3': 'Be a spiritual support for Vietnamese Catholics abroad',
    'about.activities_title': 'Community Activities',
    'about.activities_desc': 'The community has various activities to nourish faith and build community spirit.',
    'about.liturgy': 'Liturgy',
    'about.education': 'Faith Education',
    'about.community': 'Community Activities',
    'about.liturgy_1': 'Weekly Sunday Mass',
    'about.liturgy_2': 'Special liturgical ceremonies',
    'about.liturgy_3': 'Sacred music and scripture reading',
    'about.education_1': 'Catechism classes for children',
    'about.education_2': 'Youth activities',
    'about.education_3': 'Bible study',
    'about.community_1': 'Visiting elderly and sick people',
    'about.community_2': 'Social charity activities',
    'about.community_3': 'Organizing community events',
    'about.leadership': 'Pastoral Committee',
    'about.leadership_desc': 'The current Pastoral Committee of the community consists of dedicated members who serve devotedly under the guidance of the Chaplain. The Pastoral Committee members are always ready to listen and serve the needs of the faithful in the community.',
    'about.join_title': 'Join Us',
    'about.join_desc': 'The community always welcomes new members. If you want to learn more or participate in community activities, please do not hesitate to contact us.',
    'about.call': 'Call',
    'about.email': 'Send Email',
    
    // Contact
    'contact.title': 'Contact',
    'contact.get_in_touch': 'Get in Touch',
    'contact.description': 'If you have questions or need support, please contact us through the information below or attend Sunday Mass weekly.',
    'contact.address': 'Address',
    'contact.mass': 'Mass',
    'contact.phone': 'Phone',
    'contact.email': 'Email',
    'contact.facebook': 'Facebook:',
    'contact.send_message': 'Send a Message',
    'contact.name': 'Full Name',
    'contact.name_placeholder': 'Enter your name',
    'contact.email_placeholder': 'Enter your email',
    'contact.phone_placeholder': 'Enter your phone number',
    'contact.subject': 'Subject',
    'contact.subject_placeholder': 'Enter subject',
    'contact.message': 'Message',
    'contact.message_placeholder': 'Enter your message...',
    'contact.send_button': 'Send Message',
    'contact.success_message': 'Thank you! Your message has been sent successfully.',
    'contact.connect_with_us': 'Connect With Us',
    'contact.find_us': 'Find Us',
    'contact.open_map': 'Open Google Maps',
    
    // Ministries
    'ministries.title': 'Ministries',
    'ministries.description': 'St Ane Le Thi Thanh Community has various ministries serving the spiritual and life needs of the faithful.',
    'ministries.serving_together': 'Serving Together',
    'ministries.join_title': 'Join in Service',
    'ministries.join_desc': 'Every member of the community has a call to serve. Join the ministries to build God\'s Kingdom together.',
    'ministries.activities': 'Activities',
    'ministries.get_involved': 'Get Involved',
    'ministries.get_involved_desc': 'If you would like to join in service or learn more about ministries, please contact us.',
    'ministries.call_us': 'Call Us',
    'ministries.email_us': 'Email Us',

    'ministries.safeguarding_title': 'Safeguarding Policy',
    'ministries.safeguarding_heading': 'Commitment to Safeguarding Children & Vulnerable People',
    'ministries.safeguarding_desc': 'We are committed to creating a safe and supportive environment for everyone, especially children and vulnerable people. Please review our detailed policy.',
    'ministries.download_policy': 'Download Policy (PDF)',
    
    'ministries.family': 'Family Ministry',
    'ministries.family_desc': 'Organizing activities for families and children in the community, helping to build strong Catholic families.',
    'ministries.family_activity_1': 'Organizing family gatherings',
    'ministries.family_activity_2': 'Catechism classes for children',
    'ministries.family_activity_3': 'Family support and counseling',
    
    'ministries.liturgy': 'Liturgical Ministry',
    'ministries.liturgy_desc': 'Preparing and serving in masses and religious ceremonies, ensuring dignified liturgical celebrations.',
    'ministries.liturgy_activity_1': 'Serving in Mass (reading, offering gifts)',
    'ministries.liturgy_activity_2': 'Preparing and decorating the altar',
    'ministries.liturgy_activity_3': 'Organizing special ceremonies',
    
    'ministries.music': 'Choir',
    'ministries.music_desc': 'Serving music in masses and special occasions, contributing to more solemn liturgical celebrations.',
    'ministries.music_activity_1': 'Singing in Sunday Mass',
    'ministries.music_activity_2': 'Weekly choir practice',
    'ministries.music_activity_3': 'Serving in special occasions',
    
    'ministries.charity': 'Charity Ministry',
    'ministries.charity_desc': 'Supporting those in difficult circumstances in the community and society, practicing God\'s love.',
    'ministries.charity_activity_1': 'Visiting and helping the poor',
    'ministries.charity_activity_2': 'Collecting and distributing charity gifts',
    'ministries.charity_activity_3': 'Organizing charity programs',
    
    'ministries.youth': 'Youth Ministry',
    'ministries.youth_desc': 'Organizing activities for youth, helping young people develop faith and life skills.',
    'ministries.youth_activity_1': 'Regular youth activities',
    'ministries.youth_activity_2': 'Summer camps and extracurricular activities',
    'ministries.youth_activity_3': 'Bible study and catechesis',
    
    'ministries.evangelization': 'Evangelization Ministry',
    'ministries.evangelization_desc': 'Proclaiming the Gospel and inviting people to Christ, spreading faith in the community.',
    'ministries.evangelization_activity_1': 'Organizing faith sharing sessions',
    'ministries.evangelization_activity_2': 'Welcoming and guiding newcomers',
    'ministries.evangelization_activity_3': 'Distributing materials and religious books',
    
    // Homepage additional sections
    'home.welcome_title': 'Welcome to Our Community',
    'home.faith_title': 'Faith',
    'home.faith_desc': 'Growing together in worship and Catholic faith',
    'home.community_title': 'Community',
    'home.community_desc': 'Building close relationships within the Vietnamese community',
    'home.service_title': 'Service',
    'home.service_desc': 'Serving together and spreading God\'s love',
    'home.mass_schedule_title': 'Mass Times & Location',
    'home.mass_schedule_subtitle': 'Mass Schedule',
    'home.sunday': 'Sunday:',
    'home.sunday_time': '5-6pm',
    'home.special_days': 'Special feast days:',
    'home.special_days_desc': 'As announced',
    'home.confession': 'Confession:',
    'home.confession_time': '30 minutes before Mass',
    'home.info_title': 'Information',
    'home.address_label': 'Address:',
    'home.address_value': 'St Clare Catholic Church, 138 Woodhouse Grove, Box Hill North VIC 3129',
    'home.parking_label': 'Parking:',
    'home.parking_desc': 'Free parking available on church grounds',
    'home.contact_label': 'Contact:',
    'home.upcoming_events': 'Upcoming Events',
    'home.important_event': 'Important upcoming event',
    'home.featured_event': 'Featured Event',
    'home.other_events': 'Other upcoming events',
    'home.details': 'Details',
    'home.view_all_events': 'View all events',
    'home.ministries_title': 'Ministries',
    'home.children_ministry': 'Children',
    'home.children_desc': 'Catechism and activities for children',
    'home.youth_ministry': 'Youth',
    'home.youth_desc': 'Activities and sharing for young people',
    'home.family_ministry': 'Family',
    'home.family_desc': 'Accompanying young families',
    'home.choir_ministry': 'Choir',
    'home.choir_desc': 'Serving sacred music in Mass',
    'home.latest_content': 'Latest Gospel',
    'home.gospel': 'Gospel',
    'home.read_more': 'Read more',
    'home.view_all_gospel': 'View all Gospel reflections',
    'home.connect': 'Connect',
    'home.follow_us': 'Follow us',
    'home.facebook': 'Facebook',
    'home.email': 'Email',
    'home.contact_direct': 'Contact directly',
    'home.join_us_title': 'Join Us',
    'home.join_us_desc': 'We always welcome new members to join our community. Come attend Mass and participate in community activities!',
    'home.contact_now': 'Contact Now',
    'home.learn_more_about': 'Learn More',
    
    // Footer
    'footer.copyright': 'Vietnamese Catholic Community St Ane Le Thi Thanh. All rights reserved.',
    'footer.about': 'About',
    'footer.contact': 'Contact',
    'footer.description': 'St Ane Le Thi Thanh Vietnamese Catholic Community serving with faith, hope, and love.',
    'footer.quick_links': 'Quick Links',
    'footer.contact_us': 'Contact Us',
    'footer.mass_times': 'Mass Times',
    'footer.back_to_top': 'Back to Top',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms',
    'footer.sitemap': 'Sitemap',
    
    // Rich Text Editor
    'Rich Text Editor': 'Rich Text Editor',
    'Enter URL': 'Enter URL',
    'Bold (Ctrl+B)': 'Bold (Ctrl+B)',
    'Italic (Ctrl+I)': 'Italic (Ctrl+I)',
    'Underline (Ctrl+U)': 'Underline (Ctrl+U)',
    'Bullet List': 'Bullet List',
    'Numbered List': 'Numbered List',
    'Link (Ctrl+K)': 'Link (Ctrl+K)',
    'Clear Formatting': 'Clear Formatting',
    'Tip: You can paste formatted content directly from Facebook, Word, or other platforms': 'Tip: You can paste formatted content directly from Facebook, Word, or other platforms',
    'Language': 'Language',
    
    // Modern Rich Text Editor
    'Tip: Paste with Ctrl+V to preserve formatting from Facebook, Word, or other platforms': 'Tip: Paste with Ctrl+V to preserve formatting from Facebook, Word, or other platforms',
  }
};

interface LanguageProviderProps {
  children: ReactNode;
}

export function LanguageProvider({ children }: LanguageProviderProps) {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    if (saved === 'vi' || saved === 'en') return saved;
    return 'vi';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
    document.documentElement.lang = language;
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations[typeof language]] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

// eslint-disable-next-line react-refresh/only-export-components
export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
